name: Node.js Package Publish NPM

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Install TypeScript dependencies
        run: npm ci

      - run: npm publish --workspace sparx64
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: npm publish --workspace randflake
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
